export const ManagersColumns = [
  { field: "id", headerName: "ID", width: 150 },
  { field: "name", headerName: "Team Name", width: 130 },
  { field: "manager", headerName: "Name", width: 130 },

  { field: "totalAm", headerName: "Total Am", width: 90 },
  { field: "totalTl", headerName: "Total Tl", width: 90 },
  { field: "totalExecutive", headerName: "Total Executive", width: 120 },
];

export const AssistantManagersColumns = [
  { field: "id", headerName: "ID", width: 150 },
  { field: "name", headerName: "Name", width: 250 },
  { field: "managerName", headerName: "Manager", width: 170 },
];

export const TeamLeadColumns = [
  { field: "id", headerName: "ID", width: 150 },
  { field: "name", headerName: "Name", width: 160 },
  { field: "amName", headerName: "Assistant Manager", width: 180 },
  { field: "managerName", headerName: "Manager", width: 170 },
];

export const ExecutiveColumn = [
  { field: "id", headerName: "ID", width: 150 },
  { field: "name", headerName: "Name", width: 100 },
  { field: "teamLeadName", headerName: "Tl", width: 140 },
  { field: "amName", headerName: "Assistant Manager", width: 140 },
  { field: "managerName", headerName: "Manager", width: 150 },
];
export const TEAMS_DATA = [
  {
    id: "1jkkbd234232131",
    name: "Team A",
    manager: "Pardeep Kumar",
    totalAm: 2,
    totalTl: 4,
    totalExecutive: 14,
    am: [
      {
        id: "1jkkbd234232dsdsan34434q",
        name: "Mohit Sharma",
        managerName: "Pardeep Kumar",
        tl: [
          {
            id: "1jkkbd234232dsdsan34434p",
            name: "Rohit Mahajan",
            teamLeadName: "Rohit Mahajan",
            managerName: "Pardeep Kumar",
            amName: "Mohit Sharma",
            executive: [
              {
                id: "1jkkbd234232dsdsan34434n",
                name: "Bharti",
                teamLeadName: "Rohit Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
              {
                id: "1jkkbd234232dsdsan34434o",
                name: "Sandeep",
                teamLeadName: "Rohit Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
              {
                id: "1jkkbd234232dsdsan34434nf",
                name: "Koshal",
                teamLeadName: "Rohit Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
              {
                id: "1jkkbd234232dsdsan34434od",
                name: "Pryinka",
                teamLeadName: "Rohit Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
            ],
          },
          {
            id: "1jkkbd234232dsdsan34434o",
            name: "Nugen Mahajan",
            teamLeadName: "Nugen Mahajan",
            managerName: "Pardeep Kumar",
            amName: "Mohit Sharma",
            executive: [
              {
                id: "1jkkbd234232dsdsan34434l",
                name: "Parshotam",
                teamLeadName: "Nugen Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
              {
                id: "1jkkbd234232dsdsan34434m",
                name: "Gungun",
                teamLeadName: "Nugen Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
              {
                id: "1jkkbd234232dsdsan34434ns",
                name: "Mahadav",
                teamLeadName: "Nugen Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
              {
                id: "1jkkbd234232dsdsan34434ow",
                name: "Saruchi",
                teamLeadName: "Nugen Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
            ],
          },
        ],
      },
      {
        id: "1jkkbd234232dsdsan34434k",
        name: "Gurdeep Singh",
        managerName: "Pardeep Kumar",
        tl: [
          {
            id: "1jkkbd234232dsdsan34434j",
            name: "Karan Mahajan",
            teamLeadName: "Karan Mahajan",
            managerName: "Pardeep Kumar",
            amName: "Gurdeep Singh",
            executive: [
              {
                id: "1jkkbd234232dsdsan34434f",
                name: "Ram",
                teamLeadName: "Karan Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Gurdeep Singh",
              },
              {
                id: "1jkkbd234232dsdsan34434g",
                name: "Sham",
                teamLeadName: "Karan Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Gurdeep Singh",
              },
              {
                id: "1jkkbd234232dsdsan34434h",
                name: "John",
                teamLeadName: "Karan Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Gurdeep Singh",
              },
              {
                id: "1jkkbd234232dsdsan34434i",
                name: "Tom",
                teamLeadName: "Karan Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Gurdeep Singh",
              },
            ],
          },
          {
            id: "1jkkbd234232dsdsan34434jhnu",
            name: "Mohit Mahajan",
            teamLeadName: "Mohit Mahajan",
            managerName: "Pardeep Kumar",
            amName: "Gurdeep Singh",
            executive: [
              {
                id: "1jkkbd234232dsdsan34434d",
                name: "John",
                teamLeadName: "Mohit Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Gurdeep Singh",
              },
              {
                id: "1jkkbd234232dsdsan34434e",
                name: "Tom",
                teamLeadName: "Mohit Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Gurdeep Singh",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "1jkkbd234232132",
    name: "Team B",
    manager: "Hardeep Kumar",
    totalAm: 1,
    totalTl: 2,
    totalExecutive: 8,
    am: [
      {
        id: "1jkkbd234232134",
        name: "Sumit Kumar",
        managerName: "Hardeep Kumar",
        tl: [
          {
            id: "1jkkbd234232dsa13dfr",
            name: "Rohit Mahajan",
            managerName: "Hardeep Kumar",
            amName: "Sumit Kumar",
            executive: [
              {
                id: "1jkkbd234232dsdsan34434v",
                name: "Rohan",
                teamLeadName: "Rohit Mahajan",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
              {
                id: "1jkkbd234232dsafsdf32424g",
                name: "Sohan",
                teamLeadName: "Rohit Mahajan",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
              {
                id: "1jkkbd234232dsalj09782w",
                name: "Mohan",
                teamLeadName: "Rohit Mahajan",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
              {
                id: "1jkkbd234232dsacnjlbsa5s",
                name: "Gohan",
                teamLeadName: "Rohit Mahajan",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
            ],
          },
          {
            id: "1jkkbd234232dsa13dfr1",
            name: "Amandeep Kaur",
            teamLeadName: "Amandeep Kaur",
            managerName: "Hardeep Kumar",
            amName: "Sumit Kumar",
            executive: [
              {
                id: "1jkkbd234232dsdsan34434x",
                name: "Raman",
                teamLeadName: "Amandeep Kaur",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
              {
                id: "1jkkbd234232dsafsdf32424a",
                name: "Aman",
                teamLeadName: "Amandeep Kaur",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
              {
                id: "1jkkbd234232dsalj09782z",
                name: "Pawan",
                teamLeadName: "Amandeep Kaur",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
              {
                id: "1jkkbd234232dsacnjlbsa5l",
                name: "Shanav",
                teamLeadName: "Amandeep Kaur",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
            ],
          },
        ],
      },
    ],
  },
  // Added more managers below
  {
    id: "1jkkbd234232133",
    name: "Team C",
    manager: "Sandeep Kumar",
    totalAm: 3,
    totalTl: 5,
    totalExecutive: 20,
    am: [
      {
        id: "1jkkbd234232xyz",
        name: "Kavita Kumari",
        managerName: "Sandeep Kumar",
        tl: [
          {
            id: "1jkkbd234232qwe",
            name: "Ravi Singh",
            teamLeadName: "Ravi Singh",
            managerName: "Sandeep Kumar",
            amName: "Kavita Kumari",
            executive: [
              // Add Executives for this TL
            ],
          },
          {
            id: "1jkkbd234232rew",
            name: "Ajay Yadav",
            teamLeadName: "Ajay Yadav",
            managerName: "Sandeep Kumar",
            amName: "Kavita Kumari",
            executive: [
              // Add Executives for this TL
            ],
          },
        ],
      },
    ],
  },
];

export const Client_columns = [
  { field: "id", headerName: "ID", width: 70, editable: false },
  {
    field: "company",
    headerName: "Company Name",
    width: 320,
    editable: false,
  },
  {
    field: "address",
    headerName: "Address",
    width: 360,
    editable: false,
  },
  {
    field: "industry",
    headerName: "Industry/Domain",
    width: 330,
    editable: false,
  },
];

export const client_employeesColumns = [
  { field: "id", headerName: "ID", width: 70, editable: false },
  {
    field: "company",
    headerName: "Company Name",
    width: 180,
    editable: false,
  },
  {
    field: "name",
    headerName: "Employee Name",
    width: 200,
    editable: false,
  },

  {
    field: "designation",
    headerName: "Employee Desigination",
    width: 200,
    editable: false,
  },
  {
    field: "department",
    headerName: "Department",
    width: 150,
    editable: false,
  },

  {
    field: "email",
    headerName: "Email",
    width: 150,
    editable: false,
  },
  {
    field: "contact",
    headerName: "Contact",
    width: 150,
    editable: false,
  },
];

export const CLIENT_DATA = [
  {
    id: 1,
    company: "Capita Tech",
    address: "123 Tech Lane, Silicon Valley, CA",
    industry: "Technology",
    employees: [
      {
        id: 1001,
        name: "Vikas Tripathi",
        designation: "Manager",
        department: "Sales",
        email: "vikas@capitatech.com",
        contact: "9857498654",
      },
      {
        id: 1002,
        name: "Pooja Sharma",
        designation: "HR Specialist",
        department: "Human Resources",
        email: "pooja.sharma@capitatech.com",
        contact: "9988771122",
      },
      {
        id: 1003,
        name: "Ravi Patel",
        designation: "Software Engineer",
        department: "IT",
        email: "ravi.patel@capitatech.com",
        contact: "9876543210",
      },
      {
        id: 1004,
        name: "Anjali Gupta",
        designation: "Marketing Lead",
        department: "Marketing",
        email: "anjali.gupta@capitatech.com",
        contact: "9865321470",
      },
    ],
  },
  {
    id: 2,
    company: "Godrej",
    address: "12 Industrial Area, Mumbai, India",
    industry: "Manufacturing",
    employees: [
      {
        id: 2001,
        name: "Amit Mehra",
        designation: "Operations Head",
        department: "Manufacturing",
        email: "amit@godrej.com",
        contact: "9123456789",
      },
      {
        id: 2002,
        name: "Neha Jain",
        designation: "Logistics Manager",
        department: "Logistics",
        email: "neha.jain@godrej.com",
        contact: "9234567890",
      },
      {
        id: 2003,
        name: "Arjun Desai",
        designation: "Production Lead",
        department: "Manufacturing",
        email: "arjun.desai@godrej.com",
        contact: "9345678901",
      },
      {
        id: 2004,
        name: "Sanya Kapoor",
        designation: "HR Manager",
        department: "HR",
        email: "sanya.kapoor@godrej.com",
        contact: "9876123456",
      },
    ],
  },
  {
    id: 3,
    company: "Videocon",
    address: "45 Electronics Avenue, Gurgaon, India",
    industry: "Consumer Electronics",
    employees: [
      {
        id: 3001,
        name: "Sonia Kapoor",
        designation: "Senior Engineer",
        department: "R&D",
        email: "sonia@videocon.com",
        contact: "8899776655",
      },
      {
        id: 3002,
        name: "Rajesh Kumar",
        designation: "Design Lead",
        department: "Design",
        email: "rajesh@videocon.com",
        contact: "9888765432",
      },
      {
        id: 3003,
        name: "Megha Reddy",
        designation: "Marketing Lead",
        department: "Marketing",
        email: "megha@videocon.com",
        contact: "8123456789",
      },
      {
        id: 3004,
        name: "Vikram Singh",
        designation: "Product Manager",
        department: "Product Development",
        email: "vikram@videocon.com",
        contact: "7887654321",
      },
    ],
  },
  {
    id: 4,
    company: "Intel",
    address: "2200 Mission College Blvd, Santa Clara, CA",
    industry: "Semiconductors",
    employees: [
      {
        id: 4001,
        name: "John Smith",
        designation: "Product Manager",
        department: "Hardware",
        email: "john.smith@intel.com",
        contact: "7867861234",
      },
      {
        id: 4002,
        name: "Andrew Jones",
        designation: "Chip Designer",
        department: "Semiconductor Design",
        email: "andrew.jones@intel.com",
        contact: "7894561230",
      },
      {
        id: 4003,
        name: "Emma Brown",
        designation: "Software Engineer",
        department: "Software",
        email: "emma.brown@intel.com",
        contact: "7958623145",
      },
      {
        id: 4004,
        name: "Michael Clark",
        designation: "Research Scientist",
        department: "R&D",
        email: "michael.clark@intel.com",
        contact: "7569832109",
      },
    ],
  },
  {
    id: 5,
    company: "AMD",
    address: "2485 Augustine Drive, Santa Clara, CA",
    industry: "Semiconductors",
    employees: [
      {
        id: 5001,
        name: "Emily Davis",
        designation: "Software Architect",
        department: "Software",
        email: "emily.davis@amd.com",
        contact: "6786784567",
      },
      {
        id: 5002,
        name: "Robert King",
        designation: "Senior Engineer",
        department: "Engineering",
        email: "robert.king@amd.com",
        contact: "6655443322",
      },
      {
        id: 5003,
        name: "Laura Harris",
        designation: "Product Lead",
        department: "Product Management",
        email: "laura.harris@amd.com",
        contact: "6777888999",
      },
      {
        id: 5004,
        name: "James Miller",
        designation: "Systems Architect",
        department: "IT",
        email: "james.miller@amd.com",
        contact: "6611223344",
      },
    ],
  },
  {
    id: 6,
    company: "Tech Mahindra",
    address: "Sharda Centre, Pune, India",
    industry: "IT Services",
    employees: [
      {
        id: 6001,
        name: "Rajesh Kumar",
        designation: "IT Consultant",
        department: "Consulting",
        email: "rajesh@techmahindra.com",
        contact: "9988776655",
      },
      {
        id: 6002,
        name: "Sita Rani",
        designation: "Project Manager",
        department: "Project Management",
        email: "sita.rani@techmahindra.com",
        contact: "9123456789",
      },
      {
        id: 6003,
        name: "Ankit Joshi",
        designation: "Software Developer",
        department: "Software",
        email: "ankit.joshi@techmahindra.com",
        contact: "9222333444",
      },
      {
        id: 6004,
        name: "Rohit Yadav",
        designation: "Business Analyst",
        department: "Analysis",
        email: "rohit.yadav@techmahindra.com",
        contact: "9988771122",
      },
    ],
  },
];

export const events_columns = [
  {
    field: "eventName",
    headerName: "Event Name",
    width: 180,
    editable: true,
  },

  {
    field: "eventDetails",
    headerName: "Event Details",
    width: 180,
    editable: true,
  },
  {
    field: "eventDate",
    headerName: "Event Date",
    width: 120,
    type: "string",
  },
  { field: "location", headerName: "Location", width: 150 },
  { field: "organizer", headerName: "Client Name", width: 150 },
  { field: "type", headerName: "Type", width: 120 },
  { field: "beginDate", headerName: "Begin Date", width: 100 },
  { field: "endDate", headerName: "End Date", width: 100 },
  { field: "remarks", headerName: "remarks", width: 100 },
  { field: "assignedTo", headerName: "Assigned To", width: 100 },
];

export const task_columns = [
  {
    field: "taskName",
    headerName: "Task Name",
    width: 180,
    editable: true,
  },

  {
    field: "assignedTo",
    headerName: "Assigned To",
    width: 180,
    editable: true,
  },
];

export const EVENTS_DATA = [
  {
    id: 1,
    eventName: "Annual Meeting",
    eventDate: "2024-01-10",
    location: "New York",
    organizer: "John Doe",
    type: "Meeting",
    beginDate: "2024-01-18",
    endDate: "2024-01-19",
    task: [
      { id: 101, taskName: "Food Catering", assignedTo: "Soravh Mishra" },
      { id: 102, taskName: "AV Setup", assignedTo: "John Smith" },
      { id: 103, taskName: "Seating Arrangement", assignedTo: "Alice Brown" },
      { id: 104, taskName: "Guest Invitations", assignedTo: "Bob White" },
      { id: 105, taskName: "Event Documentation", assignedTo: "Charlie Black" },
    ],
  },
  {
    id: 2,
    eventName: "Tech Conference",
    eventDate: "2024-02-15",
    location: "San Francisco",
    organizer: "Jane Smith",
    type: "Conference",
    beginDate: "2024-01-19",
    endDate: "2024-01-20",
    task: [
      {
        id: 201,
        taskName: "Speaker Coordination",
        assignedTo: "Pardeep Singh",
      },
      { id: 202, taskName: "Tech Setup", assignedTo: "Ravi Kumar" },
      { id: 203, taskName: "Catering", assignedTo: "Shivani Gupta" },
      { id: 204, taskName: "Venue Decoration", assignedTo: "Sandeep Yadav" },
      { id: 205, taskName: "Event Promotion", assignedTo: "Priya Sharma" },
    ],
  },
  {
    id: 3,
    eventName: "Charity Gala",
    eventDate: "2024-03-20",
    location: "Chicago",
    organizer: "Alice Brown",
    type: "Gala",
    beginDate: "2024-03-15",
    endDate: "2024-03-16",
    task: [
      {
        id: 301,
        taskName: "Sponsorship Management",
        assignedTo: "Ellen Green",
      },
      { id: 302, taskName: "Auction Setup", assignedTo: "George King" },
      { id: 303, taskName: "Guest Registration", assignedTo: "Linda Carter" },
      { id: 304, taskName: "Food Catering", assignedTo: "Simon Powell" },
      { id: 305, taskName: "Media Coverage", assignedTo: "Sarah Lee" },
    ],
  },
  {
    id: 4,
    eventName: "Sports Day",
    eventDate: "2024-04-25",
    location: "Los Angeles",
    organizer: "Bob White",
    type: "Sports Event",
    beginDate: "2024-04-20",
    endDate: "2024-04-22",
    task: [
      { id: 401, taskName: "Team Registration", assignedTo: "Nancy Davis" },
      { id: 402, taskName: "Equipment Setup", assignedTo: "Mike Taylor" },
      { id: 403, taskName: "Food and Drinks", assignedTo: "Rachel Moore" },
      { id: 404, taskName: "Crowd Control", assignedTo: "Tom Harris" },
      {
        id: 405,
        taskName: "Scoreboard Management",
        assignedTo: "Daniel Foster",
      },
    ],
  },
  {
    id: 5,
    eventName: "Product Launch",
    eventDate: "2024-05-05",
    location: "Boston",
    organizer: "Charlie Black",
    type: "Product Launch",
    beginDate: "2024-05-01",
    endDate: "2024-05-03",
    task: [
      { id: 501, taskName: "Product Demo", assignedTo: "Harry Collins" },
      {
        id: 502,
        taskName: "Social Media Promotion",
        assignedTo: "Sophie Scott",
      },
      { id: 503, taskName: "Venue Setup", assignedTo: "Liam Martin" },
      { id: 504, taskName: "Guest Invitations", assignedTo: "Olivia Harris" },
      { id: 505, taskName: "Logistics", assignedTo: "Lucas Young" },
    ],
  },
  {
    id: 6,
    eventName: "Annual Awards Ceremony",
    eventDate: "2024-06-15",
    location: "Los Angeles",
    organizer: "Jennifer Lee",
    type: "Award Ceremony",
    beginDate: "2024-06-10",
    endDate: "2024-06-12",
    task: [
      { id: 601, taskName: "Award Trophies", assignedTo: "Kevin Clark" },
      { id: 602, taskName: "Red Carpet", assignedTo: "Sandra Wilson" },
      { id: 603, taskName: "Host and MC", assignedTo: "Grace Taylor" },
      { id: 604, taskName: "Lighting Setup", assignedTo: "Jack Lee" },
      { id: 605, taskName: "Sound and Music", assignedTo: "Mia Roberts" },
    ],
  },
  {
    id: 7,
    eventName: "Team Building Retreat",
    eventDate: "2024-07-20",
    location: "Miami",
    organizer: "Mark Davis",
    type: "Retreat",
    beginDate: "2024-07-18",
    endDate: "2024-07-19",
    task: [
      { id: 701, taskName: "Outdoor Activities", assignedTo: "Andrew King" },
      { id: 702, taskName: "Lodging Arrangements", assignedTo: "Monica Bell" },
      { id: 703, taskName: "Catering", assignedTo: "Sam Green" },
      { id: 704, taskName: "Group Facilitation", assignedTo: "Rachel Brown" },
      { id: 705, taskName: "Transportation", assignedTo: "Ethan Walker" },
    ],
  },
  {
    id: 8,
    eventName: "Fashion Show",
    eventDate: "2024-08-10",
    location: "Paris",
    organizer: "Sophia Jackson",
    type: "Fashion Event",
    beginDate: "2024-08-05",
    endDate: "2024-08-07",
    task: [
      { id: 801, taskName: "Model Selection", assignedTo: "Olivia Martin" },
      { id: 802, taskName: "Runway Setup", assignedTo: "Isabella Thomas" },
      { id: 803, taskName: "Styling", assignedTo: "Emily Hall" },
      { id: 804, taskName: "Ticketing", assignedTo: "Ella Lewis" },
      { id: 805, taskName: "Photography", assignedTo: "Lily White" },
    ],
  },
  {
    id: 9,
    eventName: "Charity Auction",
    eventDate: "2024-09-05",
    location: "London",
    organizer: "Mason Moore",
    type: "Auction",
    beginDate: "2024-09-01",
    endDate: "2024-09-03",
    task: [
      { id: 901, taskName: "Item Collection", assignedTo: "Chloe Brown" },
      { id: 902, taskName: "Bid Management", assignedTo: "David White" },
      { id: 903, taskName: "Catering", assignedTo: "James Green" },
      { id: 904, taskName: "Venue Setup", assignedTo: "Ella Clark" },
      { id: 905, taskName: "Marketing", assignedTo: "Grace Wilson" },
    ],
  },
  {
    id: 10,
    eventName: "Film Premiere",
    eventDate: "2024-10-15",
    location: "Hollywood",
    organizer: "Victor Black",
    type: "Premiere",
    beginDate: "2024-10-10",
    endDate: "2024-10-12",
    task: [
      { id: 1001, taskName: "Red Carpet", assignedTo: "Sophia Harris" },
      { id: 1002, taskName: "Seating Arrangement", assignedTo: "Michael Lee" },
      { id: 1003, taskName: "Sound and Music", assignedTo: "Olivia James" },
      { id: 1004, taskName: "Catering", assignedTo: "Lucas Brown" },
      { id: 1005, taskName: "Security", assignedTo: "Nathan Clark" },
    ],
  },
];

export const VENDORS_DATA = [
  {
    id: "1081",
    name: "Kumar Printing Press",
    address: "ABC Chownk, Complex 1, Kashmir",
    companyName: "Kumar Printing Press",
    telephone: "41518412154",
    email: "kumarpress@gmail.com",
    categories: "Bulk",
    workType: "Shirts Printing",
    headOffice: "Jammu",
    tasks: [
      {
        id: "1231",
        taskName: "Print 500 shirts",
        allocationDate: "25/11/24",
        deliveryDate: "11/12/24",
      },
      {
        id: "1234",
        taskName: "Print 1000 shirts",
        allocationDate: "01/09/24",
        deliveryDate: "04/09/24",
      },
    ],
    operationalCities: [
      { id: "0893u2", name: "Baramulla" },
      { id: "0893u4", name: "Kulgam" },
      { id: "0893u5", name: "PehalGam" },
    ],
  },
  {
    id: "1082",
    name: "Evergreen Packaging",
    address: "Street 45, Sector B, Delhi",
    companyName: "Evergreen Pack",
    telephone: "41618412155",
    email: "evergreenpack@gmail.com",
    categories: "Packaging",
    workType: "Box Packaging",
    headOffice: "Delhi",
    tasks: [
      {
        id: "2231",
        taskName: "Pack 500 boxes",
        allocationDate: "10/10/24",
        deliveryDate: "20/10/24",
      },
      {
        id: "2234",
        taskName: "Pack 2000 boxes",
        allocationDate: "05/11/24",
        deliveryDate: "10/11/24",
      },
      {
        id: "2235",
        taskName: "Pack 300 boxes",
        allocationDate: "15/11/24",
        deliveryDate: "25/11/24",
      },
    ],
    operationalCities: [
      { id: "0893u6", name: "Noida" },
      { id: "0893u7", name: "Ghaziabad" },
      { id: "0893u8", name: "Faridabad" },
    ],
  },
  {
    id: "1083",
    name: "Ferro Metal Works",
    address: "Industrial Area, Bhopal",
    companyName: "Ferro Metal",
    telephone: "41718412156",
    email: "ferrometal@gmail.com",
    categories: "Metal Fabrication",
    workType: "Steel Cutting",
    headOffice: "Bhopal",
    tasks: [
      {
        id: "3231",
        taskName: "Cut 500 steel rods",
        allocationDate: "05/12/24",
        deliveryDate: "20/12/24",
      },
      {
        id: "3234",
        taskName: "Cut 2000 steel rods",
        allocationDate: "10/12/24",
        deliveryDate: "25/12/24",
      },
    ],
    operationalCities: [
      { id: "0893u9", name: "Indore" },
      { id: "0893u10", name: "Gwalior" },
      { id: "0893u11", name: "Ujjain" },
    ],
  },
  {
    id: "1084",
    name: "Sunshine Solar Solutions",
    address: "Solar Street, Hyderabad",
    companyName: "Sunshine Solar",
    telephone: "41818412157",
    email: "sunshinesolar@gmail.com",
    categories: "Solar Installation",
    workType: "Solar Panel Installation",
    headOffice: "Hyderabad",
    tasks: [
      {
        id: "4231",
        taskName: "Install 50 solar panels",
        allocationDate: "01/12/24",
        deliveryDate: "10/12/24",
      },
      {
        id: "4234",
        taskName: "Install 100 solar panels",
        allocationDate: "15/12/24",
        deliveryDate: "20/12/24",
      },
      {
        id: "4235",
        taskName: "Install 200 solar panels",
        allocationDate: "10/01/25",
        deliveryDate: "25/01/25",
      },
    ],
    operationalCities: [
      { id: "0893u12", name: "Chennai" },
      { id: "0893u13", name: "Bangalore" },
      { id: "0893u14", name: "Hyderabad" },
    ],
  },
  {
    id: "1085",
    name: "Elite Security Services",
    address: "Safety Road, Pune",
    companyName: "Elite Security",
    telephone: "41918412158",
    email: "elitesecurity@gmail.com",
    categories: "Security",
    workType: "Security Guard Services",
    headOffice: "Pune",
    tasks: [
      {
        id: "5231",
        taskName: "Provide security at 3 locations",
        allocationDate: "01/12/24",
        deliveryDate: "31/12/24",
      },
      {
        id: "5234",
        taskName: "Provide security at 5 locations",
        allocationDate: "10/01/25",
        deliveryDate: "20/01/25",
      },
    ],
    operationalCities: [
      { id: "0893u15", name: "Mumbai" },
      { id: "0893u16", name: "Navi Mumbai" },
      { id: "0893u17", name: "Pune" },
    ],
  },
  {
    id: "1086",
    name: "Modern Construction Ltd.",
    address: "Builder Lane, Kolkata",
    companyName: "Modern Construction",
    telephone: "42018412159",
    email: "modernconstruction@gmail.com",
    categories: "Construction",
    workType: "Building Construction",
    headOffice: "Kolkata",
    tasks: [
      {
        id: "6231",
        taskName: "Build 2 residential buildings",
        allocationDate: "01/01/25",
        deliveryDate: "30/06/25",
      },
      {
        id: "6234",
        taskName: "Construct 1 office building",
        allocationDate: "15/01/25",
        deliveryDate: "30/07/25",
      },
    ],
    operationalCities: [
      { id: "0893u18", name: "Kolkata" },
      { id: "0893u19", name: "Howrah" },
      { id: "0893u20", name: "Durgapur" },
    ],
  },
  {
    id: "1087",
    name: "Green Earth Landscaping",
    address: "Park Avenue, Chennai",
    companyName: "Green Earth",
    telephone: "42118412160",
    email: "greenearthlandscaping@gmail.com",
    categories: "Landscaping",
    workType: "Garden Design",
    headOffice: "Chennai",
    tasks: [
      {
        id: "7231",
        taskName: "Design garden for villa",
        allocationDate: "20/11/24",
        deliveryDate: "25/11/24",
      },
      {
        id: "7234",
        taskName: "Design garden for office complex",
        allocationDate: "01/12/24",
        deliveryDate: "10/12/24",
      },
    ],
    operationalCities: [
      { id: "0893u21", name: "Chennai" },
      { id: "0893u22", name: "Coimbatore" },
      { id: "0893u23", name: "Madurai" },
    ],
  },
  {
    id: "1088",
    name: "Swift Transport Ltd.",
    address: "Cargo Street, Ahmedabad",
    companyName: "Swift Transport",
    telephone: "42218412161",
    email: "swifttransport@gmail.com",
    categories: "Logistics",
    workType: "Freight Services",
    headOffice: "Ahmedabad",
    tasks: [
      {
        id: "8231",
        taskName: "Deliver 100 tons of freight",
        allocationDate: "10/11/24",
        deliveryDate: "20/11/24",
      },
      {
        id: "8234",
        taskName: "Deliver 500 tons of freight",
        allocationDate: "01/12/24",
        deliveryDate: "10/12/24",
      },
    ],
    operationalCities: [
      { id: "0893u24", name: "Surat" },
      { id: "0893u25", name: "Vadodara" },
      { id: "0893u26", name: "Rajkot" },
    ],
  },
  {
    id: "1089",
    name: "Zenith Electronics",
    address: "Tech Park, Bengaluru",
    companyName: "Zenith Electronics",
    telephone: "42318412162",
    email: "zenith@gmail.com",
    categories: "Electronics",
    workType: "Product Assembly",
    headOffice: "Bengaluru",
    tasks: [
      {
        id: "9231",
        taskName: "Assemble 1000 units",
        allocationDate: "05/12/24",
        deliveryDate: "15/12/24",
      },
      {
        id: "9234",
        taskName: "Assemble 5000 units",
        allocationDate: "10/12/24",
        deliveryDate: "20/12/24",
      },
    ],
    operationalCities: [
      { id: "0893u27", name: "Mysore" },
      { id: "0893u28", name: "Hubli" },
      { id: "0893u29", name: "Tumkur" },
    ],
  },
];
