export const ManagersColumns = [
  { field: "name", headerName: "Team Name", width: 130 },
  { field: "desc", headerName: "Description", width: 130 },
  { field: "manager", headerName: "Manager", width: 130 },
  { field: "totalTl", headerName: "Total TL", width: 90 },
  { field: "totalExecutive", headerName: "Total Executive", width: 120 },
];

export const AssistantManagersColumns = [
  { field: "name", headerName: "Name", width: 250 },
  { field: "managerName", headerName: "Manager", width: 170 },
];

export const TeamLeadColumns = [
  { field: "name", headerName: "Name", width: 160 },
  { field: "amName", headerName: "Assistant Manager", width: 180 },
  { field: "managerName", headerName: "Manager", width: 170 },
];

export const ExecutiveColumn = [
  { field: "name", headerName: "Name", width: 100 },
  { field: "teamLeadName", headerName: "Tl", width: 140 },
  { field: "amName", headerName: "Assistant Manager", width: 140 },
  { field: "managerName", headerName: "Manager", width: 150 },
];

export const TeamMembersColumns = [
  { field: "name", headerName: "Name", width: 200 },
  { field: "role", headerName: "Role", width: 200 },
].map((c) => ({ ...c, editable: true }));

export const TEAMS_DATA = [
  {
    id: "1jkkbd234232131",
    name: "Team A",
    manager: "Chris Evans",
    desc: "DEV Team",
    totalAm: 2,
    totalTl: 4,
    totalExecutive: 14,
    am: [
      {
        id: "1jkkbd234232dsdsan34434q",
        name: "Mohit Sharma",
        managerName: "Pardeep Kumar",
        tl: [
          {
            id: "1jkkbd234232dsdsan34434p",
            name: "Rohit Mahajan",
            teamLeadName: "Rohit Mahajan",
            managerName: "Pardeep Kumar",
            amName: "Mohit Sharma",
            executive: [
              {
                id: "1jkkbd234232dsdsan34434n",
                name: "Bharti",
                teamLeadName: "Rohit Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
              {
                id: "1jkkbd234232dsdsan34434o",
                name: "Sandeep",
                teamLeadName: "Rohit Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
              {
                id: "1jkkbd234232dsdsan34434nf",
                name: "Koshal",
                teamLeadName: "Rohit Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
              {
                id: "1jkkbd234232dsdsan34434od",
                name: "Pryinka",
                teamLeadName: "Rohit Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
            ],
          },
          {
            id: "1jkkbd234232dsdsan34434o",
            name: "Nugen Mahajan",
            teamLeadName: "Nugen Mahajan",
            managerName: "Pardeep Kumar",
            amName: "Mohit Sharma",
            executive: [
              {
                id: "1jkkbd234232dsdsan34434l",
                name: "Parshotam",
                teamLeadName: "Nugen Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
              {
                id: "1jkkbd234232dsdsan34434m",
                name: "Gungun",
                teamLeadName: "Nugen Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
              {
                id: "1jkkbd234232dsdsan34434ns",
                name: "Mahadav",
                teamLeadName: "Nugen Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
              {
                id: "1jkkbd234232dsdsan34434ow",
                name: "Saruchi",
                teamLeadName: "Nugen Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Mohit Sharma",
              },
            ],
          },
        ],
      },
      {
        id: "1jkkbd234232dsdsan34434k",
        name: "Gurdeep Singh",
        managerName: "Pardeep Kumar",
        tl: [
          {
            id: "1jkkbd234232dsdsan34434j",
            name: "Karan Mahajan",
            teamLeadName: "Karan Mahajan",
            managerName: "Pardeep Kumar",
            amName: "Gurdeep Singh",
            executive: [
              {
                id: "1jkkbd234232dsdsan34434f",
                name: "Ram",
                teamLeadName: "Karan Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Gurdeep Singh",
              },
              {
                id: "1jkkbd234232dsdsan34434g",
                name: "Sham",
                teamLeadName: "Karan Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Gurdeep Singh",
              },
              {
                id: "1jkkbd234232dsdsan34434h",
                name: "John",
                teamLeadName: "Karan Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Gurdeep Singh",
              },
              {
                id: "1jkkbd234232dsdsan34434i",
                name: "Tom",
                teamLeadName: "Karan Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Gurdeep Singh",
              },
            ],
          },
          {
            id: "1jkkbd234232dsdsan34434jhnu",
            name: "Mohit Mahajan",
            teamLeadName: "Mohit Mahajan",
            managerName: "Pardeep Kumar",
            amName: "Gurdeep Singh",
            executive: [
              {
                id: "1jkkbd234232dsdsan34434d",
                name: "John",
                teamLeadName: "Mohit Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Gurdeep Singh",
              },
              {
                id: "1jkkbd234232dsdsan34434e",
                name: "Tom",
                teamLeadName: "Mohit Mahajan",
                managerName: "Pardeep Kumar",
                amName: "Gurdeep Singh",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "1jkkbd234232132",
    name: "Team B",
    manager: "Lucas Harris",
    totalAm: 1,
    totalTl: 2,
    desc: "QA Team",
    totalExecutive: 8,
    am: [
      {
        id: "1jkkbd234232134",
        name: "Sumit Kumar",
        managerName: "Hardeep Kumar",
        tl: [
          {
            id: "1jkkbd234232dsa13dfr",
            name: "Rohit Mahajan",
            managerName: "Hardeep Kumar",
            amName: "Sumit Kumar",
            executive: [
              {
                id: "1jkkbd234232dsdsan34434v",
                name: "Rohan",
                teamLeadName: "Rohit Mahajan",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
              {
                id: "1jkkbd234232dsafsdf32424g",
                name: "Sohan",
                teamLeadName: "Rohit Mahajan",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
              {
                id: "1jkkbd234232dsalj09782w",
                name: "Mohan",
                teamLeadName: "Rohit Mahajan",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
              {
                id: "1jkkbd234232dsacnjlbsa5s",
                name: "Gohan",
                teamLeadName: "Rohit Mahajan",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
            ],
          },
          {
            id: "1jkkbd234232dsa13dfr1",
            name: "Amandeep Kaur",
            teamLeadName: "Amandeep Kaur",
            managerName: "Hardeep Kumar",
            amName: "Sumit Kumar",
            executive: [
              {
                id: "1jkkbd234232dsdsan34434x",
                name: "Raman",
                teamLeadName: "Amandeep Kaur",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
              {
                id: "1jkkbd234232dsafsdf32424a",
                name: "Aman",
                teamLeadName: "Amandeep Kaur",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
              {
                id: "1jkkbd234232dsalj09782z",
                name: "Pawan",
                teamLeadName: "Amandeep Kaur",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
              {
                id: "1jkkbd234232dsacnjlbsa5l",
                name: "Shanav",
                teamLeadName: "Amandeep Kaur",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "1jkkbd234232133",
    name: "Team C",
    manager: "William Phillips",
    totalAm: 1,
    totalTl: 2,
    desc: "PROD Team",
    totalExecutive: 0,
    am: [
      {
        id: "1jkkbd234232xyz",
        name: "Kavita Kumari",
        managerName: "Sandeep Kumar",
        tl: [
          {
            id: "1jkkbd234232qwe",
            name: "Ravi Singh",
            teamLeadName: "Ravi Singh",
            managerName: "Sandeep Kumar",
            amName: "Kavita Kumari",
            executive: [
              {
                id: "1jkkbd234232dsalj09782z",
                name: "Pawan",
                teamLeadName: "Amandeep Kaur",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
              {
                id: "1jkkbd234232dsacnjlbsa5l",
                name: "Shanav",
                teamLeadName: "Amandeep Kaur",
                managerName: "Hardeep Kumar",
                amName: "Sumit Kumar",
              },
            ],
          },
        ],
      },
    ],
  },
];

export const Client_columns = [
  {
    field: "company",
    headerName: "Company Name",
    width: 320,
    editable: false,
  },
  {
    field: "address",
    headerName: "Address",
    width: 360,
    editable: false,
  },
  {
    field: "industry",
    headerName: "Industry",
    width: 330,
    editable: false,
  },
];

export const client_employeesColumns = [
  {
    field: "name",
    headerName: "Employee Name",
    width: 200,
    editable: false,
  },

  {
    field: "designation",
    headerName: "Employee Desigination",
    width: 200,
    editable: false,
  },
  {
    field: "department",
    headerName: "Department",
    width: 150,
    editable: false,
  },

  {
    field: "email",
    headerName: "Email",
    width: 250,
    editable: false,
  },
  {
    field: "contact",
    headerName: "Contact",
    width: 100,
    editable: false,
  },
];

export const CLIENT_DATA = [
  {
    id: 1,
    company: "Capita Tech",
    address: "123 Tech Lane, Silicon Valley, CA",
    industry: "Technology",
    employees: [
      {
        id: 1001,
        name: "Vikas Tripathi",
        designation: "Manager",
        department: "Sales",
        email: "vikas@capitatech.com",
        contact: "9857498654",
      },
      {
        id: 1002,
        name: "Pooja Sharma",
        designation: "HR Specialist",
        department: "Human Resources",
        email: "pooja.sharma@capitatech.com",
        contact: "9988771122",
      },
      {
        id: 1003,
        name: "Ravi Patel",
        designation: "Software Engineer",
        department: "IT",
        email: "ravi.patel@capitatech.com",
        contact: "9876543210",
      },
      {
        id: 1004,
        name: "Anjali Gupta",
        designation: "Marketing Lead",
        department: "Marketing",
        email: "anjali.gupta@capitatech.com",
        contact: "9865321470",
      },
    ],
  },
  {
    id: 2,
    company: "Godrej",
    address: "12 Industrial Area, Mumbai, India",
    industry: "Manufacturing",
    employees: [
      {
        id: 2001,
        name: "Amit Mehra",
        designation: "Operations Head",
        department: "Manufacturing",
        email: "amit@godrej.com",
        contact: "9123456789",
      },
      {
        id: 2002,
        name: "Neha Jain",
        designation: "Logistics Manager",
        department: "Logistics",
        email: "neha.jain@godrej.com",
        contact: "9234567890",
      },
      {
        id: 2003,
        name: "Arjun Desai",
        designation: "Production Lead",
        department: "Manufacturing",
        email: "arjun.desai@godrej.com",
        contact: "9345678901",
      },
      {
        id: 2004,
        name: "Sanya Kapoor",
        designation: "HR Manager",
        department: "HR",
        email: "sanya.kapoor@godrej.com",
        contact: "9876123456",
      },
    ],
  },
  {
    id: 3,
    company: "Videocon",
    address: "45 Electronics Avenue, Gurgaon, India",
    industry: "Consumer Electronics",
    employees: [
      {
        id: 3001,
        name: "Sonia Kapoor",
        designation: "Senior Engineer",
        department: "R&D",
        email: "sonia@videocon.com",
        contact: "8899776655",
      },
      {
        id: 3002,
        name: "Rajesh Kumar",
        designation: "Design Lead",
        department: "Design",
        email: "rajesh@videocon.com",
        contact: "9888765432",
      },
      {
        id: 3003,
        name: "Megha Reddy",
        designation: "Marketing Lead",
        department: "Marketing",
        email: "megha@videocon.com",
        contact: "8123456789",
      },
      {
        id: 3004,
        name: "Vikram Singh",
        designation: "Product Manager",
        department: "Product Development",
        email: "vikram@videocon.com",
        contact: "7887654321",
      },
    ],
  },
  {
    id: 4,
    company: "Intel",
    address: "2200 Mission College Blvd, Santa Clara, CA",
    industry: "Semiconductors",
    employees: [
      {
        id: 4001,
        name: "John Smith",
        designation: "Product Manager",
        department: "Hardware",
        email: "john.smith@intel.com",
        contact: "7867861234",
      },
      {
        id: 4002,
        name: "Andrew Jones",
        designation: "Chip Designer",
        department: "Semiconductor Design",
        email: "andrew.jones@intel.com",
        contact: "7894561230",
      },
      {
        id: 4003,
        name: "Emma Brown",
        designation: "Software Engineer",
        department: "Software",
        email: "emma.brown@intel.com",
        contact: "7958623145",
      },
      {
        id: 4004,
        name: "Michael Clark",
        designation: "Research Scientist",
        department: "R&D",
        email: "michael.clark@intel.com",
        contact: "7569832109",
      },
    ],
  },
  {
    id: 5,
    company: "AMD",
    address: "2485 Augustine Drive, Santa Clara, CA",
    industry: "Semiconductors",
    employees: [
      {
        id: 5001,
        name: "Emily Davis",
        designation: "Software Architect",
        department: "Software",
        email: "emily.davis@amd.com",
        contact: "6786784567",
      },
      {
        id: 5002,
        name: "Robert King",
        designation: "Senior Engineer",
        department: "Engineering",
        email: "robert.king@amd.com",
        contact: "6655443322",
      },
      {
        id: 5003,
        name: "Laura Harris",
        designation: "Product Lead",
        department: "Product Management",
        email: "laura.harris@amd.com",
        contact: "6777888999",
      },
      {
        id: 5004,
        name: "James Miller",
        designation: "Systems Architect",
        department: "IT",
        email: "james.miller@amd.com",
        contact: "6611223344",
      },
    ],
  },
  {
    id: 6,
    company: "Tech Mahindra",
    address: "Sharda Centre, Pune, India",
    industry: "IT Services",
    employees: [
      {
        id: 6001,
        name: "Rajesh Kumar",
        designation: "IT Consultant",
        department: "Consulting",
        email: "rajesh@techmahindra.com",
        contact: "9988776655",
      },
      {
        id: 6002,
        name: "Sita Rani",
        designation: "Project Manager",
        department: "Project Management",
        email: "sita.rani@techmahindra.com",
        contact: "9123456789",
      },
      {
        id: 6003,
        name: "Ankit Joshi",
        designation: "Software Developer",
        department: "Software",
        email: "ankit.joshi@techmahindra.com",
        contact: "9222333444",
      },
      {
        id: 6004,
        name: "Rohit Yadav",
        designation: "Business Analyst",
        department: "Analysis",
        email: "rohit.yadav@techmahindra.com",
        contact: "9988771122",
      },
    ],
  },
];

export const events_columns = [
  {
    field: "eventName",
    headerName: "Event Name",
    width: 180,
    editable: true,
  },
  {
    field: "eventDetails",
    headerName: "Event Details",
    width: 180,
    editable: true,
  },

  { field: "organizer", headerName: "Client", width: 150 },
  { field: "location", headerName: "Location", width: 150 },
  { field: "type", headerName: "Type", width: 120 },
  { field: "status", headerName: "Status", width: 120 },
  { field: "assignedTo", headerName: "Assigned To", width: 100 },
  {
    field: "eventDate",
    headerName: "Event Date",
    width: 120,
    type: "string",
  },
  { field: "beginDate", headerName: "Begin Date", width: 100 },
  { field: "endDate", headerName: "End Date", width: 100 },
];

export const task_columns = [
  {
    field: "taskName",
    headerName: "Task Name",
    width: 180,
    editable: true,
  },

  {
    field: "assignedTo",
    headerName: "Assigned To",
    width: 180,
    editable: true,
  },
];

export const EVENTS_DATA = [
  {
    id: 1,
    eventName: "Annual Meeting",
    eventDetails:
      "This is the annual meeting of the organization to discuss the year's progress and future goals.",
    eventDate: "2024-01-10",
    location: "New York",
    organizer: "Godrej",
    type: "Meetings",
    beginDate: "2024-01-18",
    endDate: "2024-01-19",
    status: "Pending",
    assignedTo: "Chris Evans",
    task: [
      { id: 101, taskName: "Food Catering", assignedTo: "Soravh Mishra" },
      { id: 102, taskName: "AV Setup", assignedTo: "John Smith" },
      { id: 103, taskName: "Seating Arrangement", assignedTo: "Alice Brown" },
      { id: 104, taskName: "Guest Invitations", assignedTo: "Bob White" },
      { id: 105, taskName: "Event Documentation", assignedTo: "Charlie Black" },
    ],
  },
  {
    id: 2,
    eventName: "Tech Conference",
    eventDetails:
      "A conference showcasing the latest developments in technology, bringing together industry leaders and innovators.",
    eventDate: "2024-02-15",
    location: "San Francisco",
    organizer: "Capita Tech",
    type: "Conference",
    beginDate: "2024-01-19",
    endDate: "2024-01-20",
    status: "Ongoing",
    assignedTo: "Lucas Harris",
    task: [
      {
        id: 201,
        taskName: "Speaker Coordination",
        assignedTo: "Pardeep Singh",
      },
      { id: 202, taskName: "Tech Setup", assignedTo: "Ravi Kumar" },
      { id: 203, taskName: "Catering", assignedTo: "Shivani Gupta" },
      { id: 204, taskName: "Venue Decoration", assignedTo: "Sandeep Yadav" },
      { id: 205, taskName: "Event Promotion", assignedTo: "Priya Sharma" },
    ],
  },
  {
    id: 3,
    eventName: "Charity Gala",
    eventDetails:
      "A fundraising event featuring a lavish dinner and entertainment to support various charitable causes.",
    eventDate: "2024-03-20",
    location: "Chicago",
    organizer: "Videocon",
    type: "Gala",
    beginDate: "2024-03-15",
    endDate: "2024-03-16",
    status: "Not Started",
    assignedTo: "William Phillips",
    task: [
      {
        id: 301,
        taskName: "Sponsorship Management",
        assignedTo: "Ellen Green",
      },
      { id: 302, taskName: "Auction Setup", assignedTo: "George King" },
      { id: 303, taskName: "Guest Registration", assignedTo: "Linda Carter" },
      { id: 304, taskName: "Food Catering", assignedTo: "Simon Powell" },
      { id: 305, taskName: "Media Coverage", assignedTo: "Sarah Lee" },
    ],
  },
  {
    id: 4,
    eventName: "Sports Day",
    eventDetails:
      "A day of outdoor sports and friendly competition designed to boost team spirit and fitness.",
    eventDate: "2024-04-25",
    location: "Los Angeles",
    organizer: "Intel",
    type: "Sports Event",
    beginDate: "2024-04-20",
    endDate: "2024-04-22",
    status: "Pending",
    assignedTo: "Sophia Miller",
    task: [
      { id: 401, taskName: "Team Registration", assignedTo: "Nancy Davis" },
      { id: 402, taskName: "Equipment Setup", assignedTo: "Mike Taylor" },
      { id: 403, taskName: "Food and Drinks", assignedTo: "Rachel Moore" },
      { id: 404, taskName: "Crowd Control", assignedTo: "Tom Harris" },
      {
        id: 405,
        taskName: "Scoreboard Management",
        assignedTo: "Daniel Foster",
      },
    ],
  },
  {
    id: 5,
    eventName: "Product Launch",
    eventDetails:
      "A highly anticipated product launch event to unveil a new groundbreaking product to the market.",
    eventDate: "2024-05-05",
    location: "Boston",
    organizer: "AMD",
    type: "Product Launch",
    beginDate: "2024-05-01",
    endDate: "2024-05-03",
    status: "Not Started",
    assignedTo: "William Phillips",
    task: [
      { id: 501, taskName: "Product Demo", assignedTo: "Harry Collins" },
      {
        id: 502,
        taskName: "Social Media Promotion",
        assignedTo: "Sophie Scott",
      },
      { id: 503, taskName: "Venue Setup", assignedTo: "Liam Martin" },
      { id: 504, taskName: "Guest Invitations", assignedTo: "Olivia Harris" },
      { id: 505, taskName: "Logistics", assignedTo: "Lucas Young" },
    ],
  },
  {
    id: 6,
    eventName: "Annual Awards Ceremony",
    eventDetails:
      "A prestigious event recognizing the achievements of employees and celebrating the year's successes.",
    eventDate: "2024-06-15",
    location: "Los Angeles",
    organizer: "Tech Mahindra",
    type: "Award Ceremony",
    beginDate: "2024-06-10",
    endDate: "2024-06-12",
    status: "Pending",
    assignedTo: "Lucas Harris",
    task: [
      { id: 601, taskName: "Award Trophies", assignedTo: "Kevin Clark" },
      { id: 602, taskName: "Red Carpet", assignedTo: "Sandra Wilson" },
      { id: 603, taskName: "Host and MC", assignedTo: "Grace Taylor" },
      { id: 604, taskName: "Lighting Setup", assignedTo: "Jack Lee" },
      { id: 605, taskName: "Sound and Music", assignedTo: "Mia Roberts" },
    ],
  },
  {
    id: 7,
    eventName: "Team Building Retreat",
    eventDetails:
      "A retreat designed for team bonding, with activities that promote collaboration and communication.",
    eventDate: "2024-07-20",
    location: "Miami",
    organizer: "Capita Tech",
    type: "Retreat",
    beginDate: "2024-07-18",
    endDate: "2024-07-19",
    status: "Not Started",
    assignedTo: "Charlotte Lee",
    task: [
      { id: 701, taskName: "Outdoor Activities", assignedTo: "Andrew King" },
      { id: 702, taskName: "Lodging Arrangements", assignedTo: "Monica Bell" },
      { id: 703, taskName: "Catering", assignedTo: "Sam Green" },
      { id: 704, taskName: "Group Facilitation", assignedTo: "Rachel Brown" },
      { id: 705, taskName: "Transportation", assignedTo: "Ethan Walker" },
    ],
  },
  {
    id: 8,
    eventName: "Fashion Show",
    eventDetails:
      "An exciting fashion event where top designers showcase their latest collections.",
    eventDate: "2024-08-10",
    location: "Paris",
    organizer: "AMD",
    type: "Fashion Event",
    beginDate: "2024-08-05",
    endDate: "2024-08-07",
    status: "Not Started",
    assignedTo: "William Phillips",
    task: [
      { id: 801, taskName: "Model Selection", assignedTo: "Olivia Martin" },
      { id: 802, taskName: "Runway Setup", assignedTo: "Isabella Thomas" },
      { id: 803, taskName: "Styling", assignedTo: "Emily Hall" },
      { id: 804, taskName: "Ticketing", assignedTo: "Ella Lewis" },
      { id: 805, taskName: "Photography", assignedTo: "Lily White" },
    ],
  },
  {
    id: 9,
    eventName: "Charity Auction",
    eventDetails:
      "An event where attendees can bid on exclusive items, with proceeds going to charity.",
    eventDate: "2024-09-05",
    location: "London",
    organizer: "Tach Mahindra",
    type: "Auction",
    beginDate: "2024-09-01",
    endDate: "2024-09-03",
    status: "Not Started",
    assignedTo: "Lucas Harris",
    task: [
      { id: 901, taskName: "Item Collection", assignedTo: "Chloe Brown" },
      { id: 902, taskName: "Bid Management", assignedTo: "David White" },
      { id: 903, taskName: "Catering", assignedTo: "James Green" },
      { id: 904, taskName: "Venue Setup", assignedTo: "Ella Clark" },
      { id: 905, taskName: "Marketing", assignedTo: "Grace Wilson" },
    ],
  },
  {
    id: 10,
    eventName: "Film Premiere",
    eventDetails:
      "A glamorous premiere event to showcase a newly released film.",
    eventDate: "2024-10-15",
    location: "Hollywood",
    organizer: "Videocon",
    type: "Premiere",
    beginDate: "2024-10-10",
    endDate: "2024-10-12",
    status: "Not Started",
    task: [
      { id: 1001, taskName: "Red Carpet", assignedTo: "Sophia Harris" },
      { id: 1002, taskName: "Seating Arrangement", assignedTo: "Michael Lee" },
      { id: 1003, taskName: "Sound and Music", assignedTo: "Olivia James" },
      { id: 1004, taskName: "Catering", assignedTo: "Lucas Brown" },
      { id: 1005, taskName: "Security", assignedTo: "Nathan Clark" },
    ],
  },
  {
    id: 11,
    eventName: "Marketing Summit",
    eventDetails:
      "A summit focusing on the latest trends and strategies in digital marketing.",
    eventDate: "2024-11-10",
    location: "New York",
    organizer: "Tech Innovators",
    type: "Summit",
    beginDate: "2024-11-05",
    endDate: "2024-11-07",
    status: "Not Started",
    task: [
      {
        id: 1101,
        taskName: "Keynote Speaker Coordination",
        assignedTo: "Alice White",
      },
      { id: 1102, taskName: "Venue Booking", assignedTo: "John Green" },
      {
        id: 1103,
        taskName: "Marketing Collateral",
        assignedTo: "Samantha Black",
      },
      { id: 1104, taskName: "Audience Engagement", assignedTo: "David Brown" },
      {
        id: 1105,
        taskName: "Live Streaming Setup",
        assignedTo: "Olivia Smith",
      },
    ],
  },
  {
    id: 12,
    eventName: "Music Festival",
    eventDetails:
      "A multi-day music festival featuring performances from popular artists.",
    eventDate: "2024-12-05",
    location: "Austin",
    organizer: "Soundwaves",
    type: "Festival",
    beginDate: "2024-12-01",
    endDate: "2024-12-04",
    status: "Not Started",
    task: [
      {
        id: 1201,
        taskName: "Artist Coordination",
        assignedTo: "Emily Johnson",
      },
      { id: 1202, taskName: "Stage Setup", assignedTo: "Liam Davis" },
      { id: 1203, taskName: "Ticketing", assignedTo: "Robert Lee" },
      { id: 1204, taskName: "Security", assignedTo: "Grace Martinez" },
      { id: 1205, taskName: "Catering", assignedTo: "James Wilson" },
    ],
  },
  {
    id: 13,
    eventName: "Gala Dinner",
    eventDetails:
      "A formal dinner with entertainment, where key individuals are honored for their contributions.",
    eventDate: "2024-11-25",
    location: "London",
    organizer: "Royal Events",
    type: "Gala",
    beginDate: "2024-11-20",
    endDate: "2024-11-22",
    status: "Ongoing",
    assignedTo: "Lucas Harris",
    task: [
      { id: 1301, taskName: "Invitations", assignedTo: "Oliver King" },
      { id: 1302, taskName: "Venue Decoration", assignedTo: "Sophia Taylor" },
      { id: 1303, taskName: "Catering", assignedTo: "Ella Scott" },
      { id: 1304, taskName: "Entertainment", assignedTo: "Michael Harris" },
      { id: 1305, taskName: "Guest Speakers", assignedTo: "Lucy Walker" },
    ],
  },
];

export const VENDORS_DATA = [
  {
    id: "1081",
    name: "Kumar Printing Press",
    address: "ABC Chownk, Complex 1, Kashmir",
    companyName: "Kumar Printing Press",
    telephone: "41518412154",
    email: "kumarpress@gmail.com",
    categories: "Printing",
    workType: "Shirts Printing",
    headOffice: "Jammu",
    tasks: [
      {
        id: 102,
        taskName: "AV Setup",
        assignedTo: "John Smith",
        dueDate: "05/16/24",
        allocationDate: "05/01/24",
        deliveryDate: "05/20/24",
        status: "Pending",
        client: "Godrej",
        event: "Product Launch",
      },
      {
        id: 104,
        taskName: "Guest Invitations",
        assignedTo: "Bob White",
        dueDate: "05/18/24",
        allocationDate: "05/02/24",
        deliveryDate: "05/22/24",
        status: "Not Started",
        client: "Tech Mahindra",
        event: "Product Launch",
      },
      {
        id: 105,
        taskName: "Event Documentation",
        assignedTo: "Charlie Black",
        dueDate: "05/19/24",
        allocationDate: "05/03/24",
        deliveryDate: "05/23/24",
        status: "Pending",
        client: "Tech Mahindra",
        event: "Meeting",
      },
    ],
    operationalCities: [
      { id: "0893u4", name: "Kulgam" },
      { id: "0893u5", name: "PehalGam" },
    ],
    vendorEmployees: [
      {
        id: "emp1",
        name: "Rajesh Kumar",
        address: "Kashmir, Complex 2",
        contact: "9812345678",
        email: "rajesh.kumar@gmail.com",
        workCategory: "Printing",
        workType: "Shirts Printing",
      },
      {
        id: "emp2",
        name: "Priya Sharma",
        address: "Baramulla",
        contact: "9823456789",
        email: "priya.sharma@gmail.com",
        workCategory: "Printing",
        workType: "Shirts Printing",
      },
    ],
  },
  {
    id: "1082",
    name: "Evergreen Packaging",
    address: "Street 45, Sector B, Delhi",
    companyName: "Evergreen Pack",
    telephone: "41618412155",
    email: "evergreenpack@gmail.com",
    categories: "Packaging",
    workType: "Box Packaging",
    headOffice: "Delhi",
    tasks: [
      {
        id: 101,
        taskName: "Food Catering",
        assignedTo: "Soravh Mishra",
        dueDate: "05/15/24",
        allocationDate: "05/01/24",
        deliveryDate: "05/18/24",
        status: "In Progress",
        client: "Godrej",
        event: "Charity Event",
      },
    ],
    operationalCities: [
      { id: "0893u6", name: "Noida" },
      { id: "0893u7", name: "Ghaziabad" },
    ],
    vendorEmployees: [
      {
        id: "emp3",
        name: "Arjun Gupta",
        address: "Delhi, Sector B",
        contact: "9812456789",
        email: "arjun.gupta@gmail.com",
        workCategory: "Packaging",
        workType: "Box Packaging",
      },
      {
        id: "emp4",
        name: "Meera Nair",
        address: "Ghaziabad",
        contact: "9823467890",
        email: "meera.nair@gmail.com",
        workCategory: "Packaging",
        workType: "Box Packaging",
      },
    ],
  },
  {
    id: "1083",
    name: "Elite Garments",
    address: "Block C, Industrial Area, Mumbai",
    companyName: "Elite Garments Pvt Ltd",
    telephone: "41618412156",
    email: "elitegarments@gmail.com",
    categories: "Garments",
    workType: "Garments Manufacturing",
    headOffice: "Mumbai",
    tasks: [
      {
        id: 103,
        taskName: "Seating Arrangement",
        assignedTo: "Alice Brown",
        dueDate: "05/17/24",
        allocationDate: "05/04/24",
        deliveryDate: "05/21/24",
        status: "In Progress",
        client: "Godrej",
        event: "Meeting",
      },
    ],
    operationalCities: [
      { id: "0893u9", name: "Pune" },
      { id: "0893u10", name: "Nashik" },
    ],
    vendorEmployees: [
      {
        id: "emp5",
        name: "Manoj Deshmukh",
        address: "Mumbai, Block C",
        contact: "9813567890",
        email: "manoj.deshmukh@gmail.com",
        workCategory: "Garments",
        workType: "Garments Manufacturing",
      },
      {
        id: "emp6",
        name: "Sneha Patel",
        address: "Pune",
        contact: "9824567891",
        email: "sneha.patel@gmail.com",
        workCategory: "Garments",
        workType: "Garments Manufacturing",
      },
    ],
  },
];

export const TASK_COLUMNS = [
  {
    field: "taskName",
    headerName: "Task Name",
    width: 180,
    editable: true,
  },
  {
    field: "assignedTo",
    headerName: "Assigned To",
    width: 180,
    editable: true,
  },
  {
    field: "client",
    headerName: "Client",
    width: 180,
    editable: true,
  },
  {
    field: "event",
    headerName: "Event",
    width: 180,
    editable: true,
  },
  {
    field: "dueDate",
    headerName: "Due Date",
    width: 180,
    editable: true,
  },
  {
    field: "status",
    headerName: "Status",
    width: 180,
    editable: true,
  },
  {
    field: "vendor",
    headerName: "Vendor",
    width: 180,
    editable: true,
  },
];

export const TASK_DATA = [
  {
    id: 101,
    taskName: "Food Catering",
    assignedTo: "Soravh Mishra",
    dueDate: "05/15/24",
    status: "In Progress",
    vendor: "Evergreen Pack",
    client: "Godrej",
    event: "Charity Event",
  },
  {
    id: 102,
    taskName: "AV Setup",
    assignedTo: "John Smith",
    dueDate: "05/16/24",
    status: "Pending",
    vendor: "Kumar Printing Press",
    client: "Videocon",
    event: "Product Launch",
  },
  {
    id: 103,
    taskName: "Seating Arrangement",
    assignedTo: "Alice Brown",
    dueDate: "05/17/24",
    status: "In Progress",
    vendor: "",
    client: "Godrej",
    event: "Meeting",
  },
  {
    id: 104,
    taskName: "Guest Invitations",
    assignedTo: "Bob White",
    dueDate: "05/18/24",
    status: "Not Started",
    vendor: "",
    client: "Tech Mahindra",
    event: "",
  },
  {
    id: 105,
    taskName: "Event Documentation",
    assignedTo: "Charlie Black",
    dueDate: "05/19/24",
    status: "Pending",
    vendor: "Kumar Printing Press",
    client: "Tech Mahindra",
    event: "Meeting",
  },
];

export const COMMENTS_COLUMNS = [
  {
    field: "details",
    headerName: "Details",
    width: 450,
    editable: true,
  },
  {
    field: "date",
    headerName: "Date",
    width: 180,
    editable: true,
  },
  {
    field: "postedBy",
    headerName: "Posted By",
    width: 180,
    editable: true,
  },
];

export const COMMENTS_ROWS = [
  {
    id: 1,
    details: "The new feature works great!",
    date: "2024-12-10",
    postedBy: "Alice",
  },
  {
    id: 2,
    details: "Found a small bug in the UI.",
    date: "2024-12-09",
    postedBy: "Bob",
  },
  {
    id: 3,
    details: "Could we add more options to the dropdown?",
    date: "2024-12-08",
    postedBy: "Charlie",
  },
  {
    id: 4,
    details: "Documentation is clear and helpful.",
    date: "2024-12-07",
    postedBy: "Diana",
  },
  {
    id: 5,
    details: "Performance has improved significantly.",
    date: "2024-12-06",
    postedBy: "Eve",
  },
];

export const USER_COLUMNS = [
  { field: "name", headerName: "Name", width: 150 },
  { field: "role", headerName: "Role", width: 150 },
  { field: "email", headerName: "Email", width: 200 },
  { field: "contact", headerName: "Contact", width: 150 },
  { field: "designation", headerName: "Designation", width: 150 },
];

export const USER_ROWS = [
  {
    id: 5,
    name: "Chris Evans",
    role: "Manager",
    email: "chris.evans@example.com",
    contact: "789-123-4560",
    designation: "Manager",
  },
  {
    id: 13,
    name: "Lucas Harris",
    role: "Manager",
    email: "lucas.harris@example.com",
    contact: "901-234-5678",
    designation: "Manager",
  },
  {
    id: 25,
    name: "William Phillips",
    role: "Manager",
    email: "william.phillips@example.com",
    contact: "404-516-1718",
    designation: "Manager",
  },
  {
    id: 8,
    name: "Sophia Miller",
    role: "Assistant Manager",
    email: "sophia.miller@example.com",
    contact: "678-901-2345",
    designation: "Manager",
  },
  {
    id: 18,
    name: "Charlotte Lee",
    role: "Assistant Manager",
    email: "charlotte.lee@example.com",
    contact: "123-456-7899",
    designation: "Manager",
  },
  {
    id: 15,
    name: "Mason Martinez",
    role: "Team Lead",
    email: "mason.martinez@example.com",
    contact: "567-901-2345",
    designation: "Team Lead",
  },
  {
    id: 23,
    name: "Benjamin Adams",
    role: "Team Lead",
    email: "benjamin.adams@example.com",
    contact: "202-131-4151",
    designation: "Team Lead",
  },
  {
    id: 1,
    name: "John Doe",
    role: "Executive",
    email: "john.doe@example.com",
    contact: "123-456-7890",
    designation: "Executive",
  },
  {
    id: 2,
    name: "Jane Smith",
    role: "Executive",
    email: "jane.smith@example.com",
    contact: "987-654-3210",
    designation: "Executive",
  },
  {
    id: 3,
    name: "Alice Brown",
    role: "Executive",
    email: "alice.brown@example.com",
    contact: "456-789-1230",
    designation: "Executive",
  },
  {
    id: 4,
    name: "Bob Johnson",
    role: "Executive",
    email: "bob.johnson@example.com",
    contact: "654-321-0987",
    designation: "Executive",
  },
  {
    id: 6,
    name: "Emma Watson",
    role: "Executive",
    email: "emma.watson@example.com",
    contact: "321-654-9870",
    designation: "Executive",
  },
  {
    id: 7,
    name: "Liam Wilson",
    role: "Executive",
    email: "liam.wilson@example.com",
    contact: "234-567-8901",
    designation: "Executive",
  },
  {
    id: 9,
    name: "Noah Davis",
    role: "Executive",
    email: "noah.davis@example.com",
    contact: "890-123-4567",
    designation: "Executive",
  },
  {
    id: 10,
    name: "Mia Taylor",
    role: "Executive",
    email: "mia.taylor@example.com",
    contact: "567-890-1234",
    designation: "Executive",
  },
  {
    id: 11,
    name: "Ethan Moore",
    role: "Executive",
    email: "ethan.moore@example.com",
    contact: "456-123-7890",
    designation: "Executive",
  },
  {
    id: 12,
    name: "Ava White",
    role: "Executive",
    email: "ava.white@example.com",
    contact: "789-234-5671",
    designation: "Executive",
  },
  {
    id: 14,
    name: "Isabella Clark",
    role: "Executive",
    email: "isabella.clark@example.com",
    contact: "345-678-9012",
    designation: "Executive",
  },
  {
    id: 16,
    name: "Olivia Garcia",
    role: "Executive",
    email: "olivia.garcia@example.com",
    contact: "890-345-6789",
    designation: "Executive",
  },
  {
    id: 17,
    name: "Aiden Hernandez",
    role: "Executive",
    email: "aiden.hernandez@example.com",
    contact: "234-890-1234",
    designation: "Executive",
  },
  {
    id: 19,
    name: "Elijah King",
    role: "Executive",
    email: "elijah.king@example.com",
    contact: "987-654-3200",
    designation: "Executive",
  },
  {
    id: 20,
    name: "Amelia Scott",
    role: "Executive",
    email: "amelia.scott@example.com",
    contact: "345-678-9001",
    designation: "Executive",
  },
  {
    id: 21,
    name: "James Green",
    role: "Executive",
    email: "james.green@example.com",
    contact: "789-101-1121",
    designation: "Executive",
  },
  {
    id: 22,
    name: "Abigail Young",
    role: "Executive",
    email: "abigail.young@example.com",
    contact: "101-112-1314",
    designation: "Executive",
  },
  {
    id: 24,
    name: "Evelyn Baker",
    role: "Executive",
    email: "evelyn.baker@example.com",
    contact: "303-415-1617",
    designation: "Executive",
  },
  {
    id: 26,
    name: "Harper Carter",
    role: "Executive",
    email: "harper.carter@example.com",
    contact: "505-617-1819",
    designation: "Executive",
  },
  {
    id: 27,
    name: "Henry Mitchell",
    role: "Executive",
    email: "henry.mitchell@example.com",
    contact: "606-718-1920",
    designation: "Executive",
  },
  {
    id: 28,
    name: "Emily Perez",
    role: "Executive",
    email: "emily.perez@example.com",
    contact: "707-819-2021",
    designation: "Executive",
  },
  {
    id: 29,
    name: "Michael Hall",
    role: "Executive",
    email: "michael.hall@example.com",
    contact: "808-920-2122",
    designation: "Executive",
  },
  {
    id: 30,
    name: "Ella Turner",
    role: "Executive",
    email: "ella.turner@example.com",
    contact: "909-101-2223",
    designation: "Executive",
  },
];

export const HELP_DRAWER_TIPS = {
  "/vendors": [
    "The Vendors section allows you to manage all vendor-related information and tasks.",
    "Click the 'Add' toggle button to open the form and add a new vendor.",
    "Once a vendor is added, their details will appear in the vendor list table below.",
    "You can edit, delete, or view additional information for each vendor in the list.",
    "To edit and delete a vendor, click the 'Edit' or 'Delete' icon next to their records. You can update and delete vendor details in the table.",
    "Clicking on a vendor will redirect you to their Vendor Details page, where you can manage their specific details.",
    "Use this section to keep track of all vendor-related information.",
  ],
  "/activity": [
    "The Events section allows you to manage all your events in one place.",
    "To add a new event, click on the 'Create Event' toggle button, which opens a form to add the event details.",
    "Once the event details are entered and submitted, the new event will be added to the event list below.",
    "In the event list table, you can view all the events you have added.",
    "Each event record in the list can be edited or deleted as needed.",
    "To edit and delete an event, click on the 'Edit' or 'Delete' icon next to the event record. You can update and delete the event information from the table.",
    "Clicking on any record in the event list will redirect you to the Event Details page for the selected event.",
    "The Event Details page provides a detailed view of the event and allows you to manage event-specific information.",
  ],
  "/analytics": [
    "The dashboard displays three key grids: Upcoming Events, Pending Tasks, and Follow-ups.",
    "These grid provides an overview of upcoming events, pending tasks, and follow-up items.",
    "Click on any upcoming event record in the Upcoming Events grid to be redirected to the event details page.",
    "The event details page will provide detailed information about the selected event.",
    "In the Upcoming Events grid, you will find a 'View More' button in the top right corner.",
    "Clicking the 'View More' button will redirect you to the Events section.",
    "The Pending Tasks grid displays tasks that are yet to be completed.",
    "Click on any task in the Pending Tasks grid to be redirected to the task details page.",
    "Similar to the Upcoming Events grid, the Pending Tasks grid also has a 'View More' button.",
    "Click the 'View More' button to go to the Tasks section where you can see a complete list of tasks.",
    "The Follow-Ups grid shows important follow-up items that require attention.",
    "Click on a follow-up item in the Follow-Ups grid to view more details about that follow-up.",
    "Just like the other grids, the Follow-Ups grid includes a 'View More' button in the top right.",
    "Click the 'View More' button to be redirected to the clients section.",
    "The 'View More' buttons in all three grids help you access more detailed pages for events, tasks, and clients.",
    "This dashboard helps you keep track of important events, tasks, and follow-ups in one place.",
  ],
  "/clients": [
    "The Clients section allows you to manage all your clients.",
    "To add a new client, click on the 'Add' toggle button, which opens a form to add the client's details.",
    "Once the client details are entered and submitted, the new client will be added to the client list below.",
    "In the client list table, you can view all the clients you have added.",
    "Each client record in the list can be edited or deleted as needed.",
    "To edit and delete a client, click on the 'Edit' or 'Delete' icon next to the client's record. You can update and delete the client information in the form.",
    "Clicking on any record in the client list will redirect you to the Client Details page for the selected client.",
    "The Client Details page provides a detailed view of the client and allows you to manage client-specific information.",
    "This section is essential for maintaining and updating client records.",
  ],
  "/internals": [
    "The Internals section is divided into two tabs: Team Management and Users.",
    "In the Team Management tab, you can create, manage, and edit teams.",
    "In the Users tab, you can add, edit, and delete users.",
    "In Team Management, you have the option to create a team by clicking on the Create Team toggle button.",
    "Once you create a team, it will appear in the Teams Table below, where you can edit or delete existing teams.",
    "To edit and delete a team, click on the 'Edit' or 'Delete' icon next to the team record.",
    "Clicking on any team record will redirect you to the Team Details page, where you can manage further details.",
    "In the Users tab, you can create a new user by clicking the Create User toggle button.",
    "Once you click Create User, you will be able to enter the user's details such as name, role, and other relevant information.",
    "After creating a user, the user will be added to the User List below.",
    "In the User List, you can Edit or Delete any user from the list.",
    "This section helps you maintain and manage your internal operations, including team structures and user management.",
  ],
  "/sub-activity": [
    "The Tasks section allows you to manage all your tasks and their associated details.",
    "To add a new task, click on the 'Add' toggle button, which opens a form to input the task details.",
    "Once the task details are entered and submitted, the new task will be added to the task list below.",
    "In the task list table, you can view all the tasks you have added.",
    "Each task record in the list can be edited, deleted, or have comment icon.",
    "To edit and delete a task, click on the 'Edit' or 'Delete' icon next to the task record. You can update and delete the task information from the table.",
    "Each task in the list shows how many comments are associated with it. in the comment icon This helps you track discussions and updates for the task.",
    "Clicking on any task record in the list will redirect you to the Task Details page for the selected task.",
    "The Task Details page provides a detailed view of the task and allows you to manage task-specific information, including comments.",
    "This section is essential for organizing, tracking, and managing tasks, including the ability to add, edit, and delete tasks.",
  ],
  "/clients-details": [
    "You are viewing details for the selected client in the form and that you can also update",
    "You can add new employees for the client using the provided form that will open through the toggle button Add Employee",
    "You have three different sections related to this client: employees, events, and tasks.",
    "The Client Employees section allows you to view, edit, and delete employee records.",
    "The Client Events section shows all events related to the client. You can edit or delete events here.",
    "In the Client Tasks section, you can manage tasks, edit them, and delete as needed.",
    "Click on an any task to view its detailed page with full information about the task.",
    "Click on an any event to view its detailed page with full information about the event.",
    "At the Top-right of the table of the Tasks and Events we have option of 'New' through this we can add new task and event",
  ],
  "/activity-details": [
    "You are viewing details for the selected event.",
    "Review the event details, including date, location, type and etc, you can also update the event details.",
    "Toggle the 'Create Task' button to open the task creation form.",
    "The 'Task List' table below shows all tasks associated with this event.",
    "Click on any task in the list to view more details and manage it.",
    "You can edit or delete any task from the task list.",
    "Clicking on a task will redirect you to the Task Details page for further actions.",
  ],
  "/sub-activity-details": [
    "You are viewing the details of the selected task.",
    "In the Task Form section, you can assign the task to a team and select the team members responsible for the task.",
    "You can assign the task to a specific event and link it with the vendor for the task's needs.",
    "Below the task form, you will find the Add Comment section.",
    "Click the Add Comment toggle button to open the form for adding comments related to the task.",
    "You can add your comments to keep track of updates or discussions on the task.",
    "Once the comment is added, it will be displayed in the Tasks Comments table below.",
    "In the Task Comments table, you can edit or delete any comment for better task tracking.",
  ],
  "/vendors-details": [
    "The Vendor Details page allows you to view and manage information related to a specific vendor.",
    "You can update the vendor’s details through the vendor details form at the top of the page.",
    "Below the vendor details, you'll find the Add Employee toggle button.",
    "Clicking on the Add Employee toggle will open a form that allows you to add employees to the vendor.",
    "You can specify employee details and assign the work that corresponds to the vendor’s operations or needs.",
    "The Employee List table below shows all employees associated with this vendor.",
    "In this table, you can Edit or Delete any employee record.",
    "Below the Employee List table, you'll find the Task Allocated List table.",
    "In this table, you can Edit or Delete tasks related to this vendor.",
    "Clicking on any task record will redirect you to the Task Details page for that specific task.",
    "You can manage employees and tasks related to the vendor directly from the Vendor Details page.",
  ],
  "/internals-teams-details": [
    "You are viewing the details for the selected team.",
    "you can also edit the details of the team through the form that provided",
    "The Team Members table at right shows all team members assigned to the current team.",
    "You can edit or remove any team member from this table.",
    "Below the team members table, you will find the Task table.",
    "In the Task table, you can see all Task related to the team.",
    "You can edit or delete any Task from the Task table.",
  ],
};

export const SPECIAL_CASES_TIPS = {
  "/internals": [
    "Role of the user can only be updated if the user is not a part of any team.",
  ],
};
